@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

@baseURL = http://{{host}}/api/v1

###

# @name postGachaMachine
POST {{baseURL}}/gacha-machine HTTP/1.1
content-type: {{contentType}}

{
  "name": "Gacha Machine 1",
  "description": "Gacha Machine 1 Description",
  "price": "200",
  "maxStock": "100"
}

@gachaMachineId = {{postGachaMachine.response.body.$.id.value}}

###

PUT {{baseURL}}/gacha-machine/{{gachaMachineId}}/refill/10  HTTP/1.1
content-type: {{contentType}}

###

GET {{baseURL}}/gacha-machine/{{gachaMachineId}}  HTTP/1.1

###

# @name postItem
POST {{baseURL}}/item HTTP/1.1
content-type: {{contentType}}

{
  "name": "Gacha Machine 1",
  "description": "Gacha Machine 1 Description",
  "rarity": "R"
}

@itemId = {{postItem.response.body.$.id.value}}

###

GET {{baseURL}}/item/{{itemId}}  HTTP/1.1

###

PUT {{baseURL}}/item/{{itemId}} HTTP/1.1
content-type: {{contentType}}

{
  "name": "Gacha Machine 2",
  "description": "Gacha Machine 2 Description",
  "rarity": "SR"
}
